[build]
  command = "npm install"
  publish = "public"
  functions = ".netlify/functions"
  environment = { NODE_VERSION = "18" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "ejs"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200