# netlify.toml (Versión Final Definitiva)

[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "ejs"]
  # --- LÍNEA CLAVE DE LA SOLUCIÓN ---
  # Incluimos las carpetas 'views' y 'data' en el paquete de la función.
  included_files = ["../../views/**", "../../data/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200