# netlify.toml (Versión Final Corregida)

[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "ejs"]
  # --- RUTA CORREGIDA ---
  # Las rutas son relativas a la raíz del proyecto.
  included_files = ["views/**", "data/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

